env:
  es6: true
  mongo: true

rules:
  # Rules are documented at http://eslint.org/docs/rules/
  no-cond-assign: 2
  no-console: 2
  no-control-regex: 2
  no-debugger: 2
  no-div-regex: 2
  no-dupe-args: 2
  no-dupe-keys: 2
  no-duplicate-case: 2
  no-empty-character-class: 2
  no-empty-pattern: 2
  no-ex-assign: 2
  no-extra-boolean-cast: 2
  no-extra-semi: 2
  no-fallthrough: 2
  no-func-assign: 2
  no-invalid-regexp: 2
  no-labels: 2
  no-negated-in-lhs: 2
  no-obj-calls: 2
  no-octal-escape: 2
  no-octal: 2
  no-regex-spaces: 2
  no-return-assign: 2
  no-script-url: 2
  no-self-compare: 2
  no-sequences: 2
  no-sparse-arrays: 2
  no-unexpected-multiline: 2
  no-unreachable: 2
  no-unused-expressions: 2
  no-useless-call: 2
  no-with: 2
  semi: 2
  use-isnan: 2
  valid-typeof: 2
